### ISSUE TITLE
 Espaçamento errado na porcentagem do thumb e interna da conversa

### ISSUE THREAD

**Issue by KahCosta** [gces-empjuntos/ej-server#16]
A porcentagem encontra-se muito próxima da barra nas duas telas

![image](https://user-images.githubusercontent.com/30934827/66501884-a2e09080-ea9a-11e9-8a8d-1036acfbd936.png)

**Tarefas:**
- [x] Aplicar corretamente espaçamento na porcentagem do thumb e interna da conversa

**Critérios de Aceitação:**
- [x] Porcentagem alinhada com relação a aproximidade da barra nas duas telas

**Comment by filipetoyoshima** [comment]
@ricardopoppi Estamos com dificuldade acerca de como a arquitetura do projeto lida com estilo.

Já encontramos quais tags CSS funcionam bem para resolver o problema, só nos falta incluí-las corretamente nos arquivos que centralizam os estilos. Testamos adicionando tags `style` no arquivo `.jinja2` onde os cards são renderizados, mas, por mais que mostre a viabilidade de estilização, não é a solução ideal para adição às branches oficiais.

**Comment by KahCosta** [comment]
Este problema foi resolvido na branch devel e deve ser merjada na master para solução do problema
