### ISSUE TITLE
Permitir customizar a página inicial do EJ 

### ISSUE THREAD

**Issue by KahCosta** [gces-empjuntos/ej-server#2]
Atualmente a página inicial é:

* usuários deslogados: /start
* usuários logados /conversations

**Tarefas**

- [x] Customizar página inicial do EJ via django admin

**Critérios de aceitação**

- [x] Pagina inicial editável de acordo com as necessidades do usuário
- [x] Aplicar teste para validação da operação

**Comment by thiagoiferreira** [comment]
Que tipo de customizações seriam essas? Aparência? Disposição de conteúdo?
Se for aparência, a aparência teria que ter quais critérios de customização?
Para disposição de conteúdo, seria para o usuário escolher o que aparece na página inicial? No sentido de por exemplo, tópicos criados e participados, por exemplo?

**Comment by thiagoiferreira** [comment]
E no caso, dentro dos critérios de aceitação, é listado que a tarefa deve ser editável de acordo com as necessidades do usuário, quais seriam essas?

**Comment by MatheusFilipe95** [comment]
@ricardopoppi

**Comment by ricardopoppi** [comment]
@thiagoiferreira @MatheusFilipe95 acho que podemos simplificar aqui. Minha sugestão:

1- usuário cria uma página estática seguindo a arquitetura das outras páginas estáticas
2- via django admin essa página pode ser indicada como a inicial da plataforma, a que ocupa a rota "/start"

**Comment by MatheusFilipe95** [comment]
Ficou mais claro agora, obrigado.

**Comment by thiagoiferreira** [comment]
@ricardopoppi, nós estamos tendo dificuldades para achar os arquivos em que trabalhariamos, sabe nós informar em qual pasta se encontra o mesmo, para que possamos modificar o Django Admin?

**Comment by ricardopoppi** [comment]
Nesse caso, vou pedir para o Professor Fábio explicar melhor pra vcs, pois no caso do django com hyperpython o trabalho deve ser feito em cima de rotas e templates do jinja

**Comment by MatheusFilipe95** [comment]
Mesmo com o suporte do @thiagoiferreira e o do @joao4018 não foi possível resolver essa issue.
