### ISSUE TITLE
Ativar geolocalização para a informação de Cidade/UF no perfil

### ISSUE THREAD

**Issue by Hiroshi18** [gces-empjuntos/ej-server#21]
Ativar geolocalização no login para que as informações de UF/Cidade sejam populadas automaticamente

https://github.com/ejplatform/ej-server/issues/483

**Comment by davialvb** [comment]
Acredito que essa issue está para ser resolvida no repositório oficial, pois há um PR aberto para ela.

https://github.com/ejplatform/ej-server/pull/510

**Comment by Hiroshi18** [comment]
O PR ainda esta aberto desde de 2018 o professor recomendou que todas as issues antigas sem respostas podem ser feita por nós na ultima aula
