### ISSUE TITLE
Componentização de elemento

### ISSUE THREAD

**Issue by KahCosta** [gces-empjuntos/ej-server#3]
Identificar algum elemento de frontend que se repete em várias partes do código e componentizá-lo

**Tarefas**

- [ ] Identificar elemento que se repete em mais de um arquivo
- [ ] Componentizar elemento

**Critérios de aceitação**

- [ ] Elemento pode ser reutilizado em outras telas ou arquivos

**Comment by KahCosta** [comment]
Esta issue ficará congelada por um determinado tempo, até que se tenha uma revisão das tarefas que foram determinadas no repositório oficial e decida sua real necessidade de implementação, devido o fato de a maioria dos elementos utilizados, por padrão já estarem componentizados pelo jinja!

**Comment by Hiroshi18** [comment]
Issue fechada : )
