### ISSUE TITLE
Aplicar técnicas de Clean Code no arquivo detail.jinja2

### ISSUE THREAD

**Issue by Guilherme-Aguiar** [gces-empjuntos/ej-server#40]
Realizar aplicação de técnicas de clean code no arquivo detail.jinja2.

**Caminho do arquivo:**  src/ej_conversations/jinja2/ej_conversations/detail.jinja2

**Tarefas:**
Aplicar as técnicas:
- [ ] Nomes Significativos
- [ ] Métodos/Funções
- [ ] Tratamento de Erros
- [ ] Comentários
- [ ] Formatação/Identação
- [ ] Classes

**Critérios de Aceitação:**
- [ ] Código refatorado baseado no máximo de aplicação possível das técnicas citadas acima.

**Comment by filipetoyoshima** [comment]
Duplicata da #36

**Comment by Guilherme-Aguiar** [comment]
:O
