### ISSUE TITLE
 Aplicar Técnicas de Clean Code e SOLID em Arquivos da ej_conversations

### ISSUE THREAD

**Issue by Diego-BF** [gces-empjuntos/ej-server#54]
Realizar aplicação de técnicas de clean code no arquivo rules.py.

**Caminho dos arquivos:** 
- /src/ej_conversations/rules.py
- /src/ej_conversations/math.py

**Tarefas:**
Aplicar as técnicas:
- [x] Nomes Significativos
- [ ] Métodos/Funções
- [ ] Tratamento de Erros
- [ ] Comentários
- [x] Formatação/Identação
- [ ] Classes

Aplicar as técnicas de SOLID:
- [ ] Single Responsibility Principle

**Critérios de Aceitação:**
- [ ] Código refatorado baseado no máximo de aplicação possível das técnicas citadas acima.

**Comment by filipetoyoshima** [comment]
Duplicate of #44

**Comment by Diego-BF** [comment]
@filipetoyoshima , os arquivos são diferentes. Um está na pasta ej_gamifications, enquanto o rules.py que alterei está na ej_conversations.

**Comment by filipetoyoshima** [comment]
Vi agora, foi mal! :sweat_smile:
